### PR TITLE
Tolerance param 0.4

### PR DESCRIPTION
**Pull request by Clark0**

### CODE REVIEW

**Comment by Clark0** [comment]
def compare_faces(known_face_encodings, face_encoding_to_check, tolerance=0.6):
    """
    Compare a list of face encodings against a candidate encoding to see if they match.

    :param known_face_encodings: A list of known face encodings
    :param face_encoding_to_check: A single face encoding to compare against the list
    :param tolerance: How much distance between faces to consider it a match. Lower is more strict. 0.6 is typical best performance.
    :return: A list of True/False values indicating which known_face_encodings match the face encoding to check
    """
    return list(face_distance(known_face_encodings, face_encoding_to_check) <= tolerance)

**Comment by Clark0** [comment]
```python
def compare_faces(known_face_encodings, face_encoding_to_check, tolerance=0.6):
    """
    Compare a list of face encodings against a candidate encoding to see if they match.

    :param known_face_encodings: A list of known face encodings
    :param face_encoding_to_check: A single face encoding to compare against the list
    :param tolerance: How much distance between faces to consider it a match. Lower is more strict. 0.6 is typical best performance.
    :return: A list of True/False values indicating which known_face_encodings match the face encoding to check
    """
    return list(face_distance(known_face_encodings, face_encoding_to_check) <= tolerance)
```

**Comment by Clark0** [comment]
Looks like the author suggests a default threshold value to be 0.6

**Comment by QiuHaohao** [comment]
I tried yesterday and 0.4 seems to give a reasonable performance. Feel free to experiment with different tolerance value tho!

**Comment by QiuHaohao** [comment]
Pls refer to the script I sent to the slack channel for new implementation:

```py
for face_encoding in face_encodings:
    # See if the face is a match for the known face(s)
    matches = face_recognition.compare_faces(known_face_encodings, face_encoding, tolerance=0.4)
    known_faces_names_matched = [known_face_names[i] for i in range(len(known_face_encodings)) if matches[i]]
    known_faces_encodings_matched = [known_face_encodings[i] for i in range(len(known_face_encodings)) if matches[i]]
    name = "Unknown"

    if len(known_faces_names_matched) != 0:
        face_distances = face_recognition.face_distance(known_faces_encodings_matched, face_encoding)
        best_match_index = np.argmin(face_distances)
        name = known_faces_names_matched[best_match_index]
        print(name)

    face_names.append(name)
```

We should 
1. use `compare_face` to filter out those faces that fall outside the tolerance of this face
2. we get a list of the matched faces from `1`
2.1 if the list is not empty, find the nearest face with those matched using `face_distance `.
2.2 if the list is empty, then we ignore this face.

**Comment by Clark0** [comment]
LGTM

**Pull request merged**
